
# Goal
float32 relative_yaw    # radians, +CCW relative to current heading
float32 angular_speed   # optional (rad/s), 0.0 = use default

---
# Result
# Error codes
# Note: The expected priority order of the error should match the message order
uint16 NONE=0
uint16 UNKNOWN=700
uint16 TIMEOUT=701
uint16 TF_ERROR=702
uint16 COLLISION_AHEAD=703

builtin_interfaces/Duration total_elapsed_time
uint16 error_code
string error_msg
---
# Feedback
# (empty, or maybe progress percentage if you want)
